//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * An extension of the AbstractServicingNotification which includes a reference to the facility and the loan contract to which embedded loan events apply. This abtract type should be used to 'wrap' contract-level business events.
 * 
 * <p>Java class for AbstractContractNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractContractNotification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}AbstractServicingNotification"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="facilityOutstandingsPosition" type="{http://www.fpml.org/FpML-5/master}FacilityOutstandingsPosition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractContractNotification", propOrder = {
    "facilityOutstandingsPosition"
})
@XmlSeeAlso({
    AccrualOptionChangeNotification.class,
    LcNotification.class,
    LoanContractNotification.class,
    NonRecurringFeePaymentNotification.class,
    PrepaymentNotification.class,
    RolloverNotification.class
})
public abstract class AbstractContractNotification
    extends AbstractServicingNotification
{

    protected FacilityOutstandingsPosition facilityOutstandingsPosition;

    /**
     * Gets the value of the facilityOutstandingsPosition property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityOutstandingsPosition }
     *     
     */
    public FacilityOutstandingsPosition getFacilityOutstandingsPosition() {
        return facilityOutstandingsPosition;
    }

    /**
     * Sets the value of the facilityOutstandingsPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityOutstandingsPosition }
     *     
     */
    public void setFacilityOutstandingsPosition(FacilityOutstandingsPosition value) {
        this.facilityOutstandingsPosition = value;
    }

}
