//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * An event describing a future change an accruing fee associated with a specific facility.
 * 
 * <p>Java class for AccruingFeeChange complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccruingFeeChange"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}FacilityEvent"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accruingFeeOption" type="{http://www.fpml.org/FpML-5/master}AccruingFeeOption" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccruingFeeChange", propOrder = {
    "accruingFeeOption"
})
public class AccruingFeeChange
    extends FacilityEvent
{

    protected AccruingFeeOption accruingFeeOption;

    /**
     * Gets the value of the accruingFeeOption property.
     * 
     * @return
     *     possible object is
     *     {@link AccruingFeeOption }
     *     
     */
    public AccruingFeeOption getAccruingFeeOption() {
        return accruingFeeOption;
    }

    /**
     * Sets the value of the accruingFeeOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccruingFeeOption }
     *     
     */
    public void setAccruingFeeOption(AccruingFeeOption value) {
        this.accruingFeeOption = value;
    }

}
