//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A fee calculated as the cost of breaking financing against a loan contract which is repaid early.
 * 
 * <p>Java class for BreakageFeePayment complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BreakageFeePayment"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}NonRecurringFeePayment"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="breakageFeeClaimDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="breakageFeeCalculatedBy" type="{http://www.fpml.org/FpML-5/master}BreakageCalculatedByEnum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BreakageFeePayment", propOrder = {
    "breakageFeeClaimDate",
    "breakageFeeCalculatedBy"
})
public class BreakageFeePayment
    extends NonRecurringFeePayment
{

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar breakageFeeClaimDate;
    @XmlSchemaType(name = "token")
    protected BreakageCalculatedByEnum breakageFeeCalculatedBy;

    /**
     * Gets the value of the breakageFeeClaimDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBreakageFeeClaimDate() {
        return breakageFeeClaimDate;
    }

    /**
     * Sets the value of the breakageFeeClaimDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBreakageFeeClaimDate(XMLGregorianCalendar value) {
        this.breakageFeeClaimDate = value;
    }

    /**
     * Gets the value of the breakageFeeCalculatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BreakageCalculatedByEnum }
     *     
     */
    public BreakageCalculatedByEnum getBreakageFeeCalculatedBy() {
        return breakageFeeCalculatedBy;
    }

    /**
     * Sets the value of the breakageFeeCalculatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BreakageCalculatedByEnum }
     *     
     */
    public void setBreakageFeeCalculatedBy(BreakageCalculatedByEnum value) {
        this.breakageFeeCalculatedBy = value;
    }

}
