//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Commodity Swaption.
 * 
 * <p>Java class for CommoditySwaption complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommoditySwaption"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}Product"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}BuyerSeller.model"/&gt;
 *         &lt;element name="optionType" type="{http://www.fpml.org/FpML-5/master}PutCallEnum" minOccurs="0"/&gt;
 *         &lt;element name="commoditySwap" type="{http://www.fpml.org/FpML-5/master}CommoditySwaptionUnderlying" minOccurs="0"/&gt;
 *         &lt;element name="physicalExercise" type="{http://www.fpml.org/FpML-5/master}CommodityPhysicalExercise" minOccurs="0"/&gt;
 *         &lt;element name="premium" type="{http://www.fpml.org/FpML-5/master}CommodityPremium" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}CommodityContent.model" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommoditySwaption")
public class CommoditySwaption
    extends Product
{


}
