//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The stipulation of the terms under which a custody agent will be deemed acceptable by the parties. This construct has been initially developed for the purpose of the Standard CSA.
 * 
 * <p>Java class for CustodianTerms complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustodianTerms"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="minimumAssets" type="{http://www.fpml.org/FpML-5/master}Money" minOccurs="0"/&gt;
 *         &lt;element name="minimumRating" type="{http://www.fpml.org/FpML-5/master}CreditNotations" minOccurs="0"/&gt;
 *         &lt;element name="initialDesignation" type="{http://www.fpml.org/FpML-5/master}Token" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustodianTerms", propOrder = {
    "minimumAssets",
    "minimumRating",
    "initialDesignation"
})
public class CustodianTerms {

    protected Money minimumAssets;
    protected CreditNotations minimumRating;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String initialDesignation;

    /**
     * Gets the value of the minimumAssets property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getMinimumAssets() {
        return minimumAssets;
    }

    /**
     * Sets the value of the minimumAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setMinimumAssets(Money value) {
        this.minimumAssets = value;
    }

    /**
     * Gets the value of the minimumRating property.
     * 
     * @return
     *     possible object is
     *     {@link CreditNotations }
     *     
     */
    public CreditNotations getMinimumRating() {
        return minimumRating;
    }

    /**
     * Sets the value of the minimumRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditNotations }
     *     
     */
    public void setMinimumRating(CreditNotations value) {
        this.minimumRating = value;
    }

    /**
     * Gets the value of the initialDesignation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialDesignation() {
        return initialDesignation;
    }

    /**
     * Sets the value of the initialDesignation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialDesignation(String value) {
        this.initialDesignation = value;
    }

}
