//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DifferenceTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DifferenceTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Value"/&gt;
 *     &lt;enumeration value="Reference"/&gt;
 *     &lt;enumeration value="Structure"/&gt;
 *     &lt;enumeration value="Scheme"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DifferenceTypeEnum")
@XmlEnum
public enum DifferenceTypeEnum {

    @XmlEnumValue("Value")
    VALUE("Value"),
    @XmlEnumValue("Reference")
    REFERENCE("Reference"),
    @XmlEnumValue("Structure")
    STRUCTURE("Structure"),
    @XmlEnumValue("Scheme")
    SCHEME("Scheme");
    private final String value;

    DifferenceTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DifferenceTypeEnum fromValue(String v) {
        for (DifferenceTypeEnum c: DifferenceTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
