//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * The collateral eligibility as a function of the types of asset, the maturity and rating terms.
 * 
 * <p>Java class for EligibleCollateral complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EligibleCollateral"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="eligibleAsset" type="{http://www.fpml.org/FpML-5/master}EligibleAsset" minOccurs="0"/&gt;
 *         &lt;element name="lowerMaturity" type="{http://www.fpml.org/FpML-5/master}Period" minOccurs="0"/&gt;
 *         &lt;element name="higherMaturity" type="{http://www.fpml.org/FpML-5/master}Period" minOccurs="0"/&gt;
 *         &lt;element name="minimumRating" type="{http://www.fpml.org/FpML-5/master}CreditNotations" minOccurs="0"/&gt;
 *         &lt;element name="valuationPercentage" type="{http://www.fpml.org/FpML-5/master}RestrictedPercentage" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EligibleCollateral", propOrder = {
    "eligibleAsset",
    "lowerMaturity",
    "higherMaturity",
    "minimumRating",
    "valuationPercentage"
})
public class EligibleCollateral {

    protected EligibleAsset eligibleAsset;
    protected Period lowerMaturity;
    protected Period higherMaturity;
    protected CreditNotations minimumRating;
    protected BigDecimal valuationPercentage;

    /**
     * Gets the value of the eligibleAsset property.
     * 
     * @return
     *     possible object is
     *     {@link EligibleAsset }
     *     
     */
    public EligibleAsset getEligibleAsset() {
        return eligibleAsset;
    }

    /**
     * Sets the value of the eligibleAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibleAsset }
     *     
     */
    public void setEligibleAsset(EligibleAsset value) {
        this.eligibleAsset = value;
    }

    /**
     * Gets the value of the lowerMaturity property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getLowerMaturity() {
        return lowerMaturity;
    }

    /**
     * Sets the value of the lowerMaturity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setLowerMaturity(Period value) {
        this.lowerMaturity = value;
    }

    /**
     * Gets the value of the higherMaturity property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getHigherMaturity() {
        return higherMaturity;
    }

    /**
     * Sets the value of the higherMaturity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setHigherMaturity(Period value) {
        this.higherMaturity = value;
    }

    /**
     * Gets the value of the minimumRating property.
     * 
     * @return
     *     possible object is
     *     {@link CreditNotations }
     *     
     */
    public CreditNotations getMinimumRating() {
        return minimumRating;
    }

    /**
     * Sets the value of the minimumRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditNotations }
     *     
     */
    public void setMinimumRating(CreditNotations value) {
        this.minimumRating = value;
    }

    /**
     * Gets the value of the valuationPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValuationPercentage() {
        return valuationPercentage;
    }

    /**
     * Sets the value of the valuationPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValuationPercentage(BigDecimal value) {
        this.valuationPercentage = value;
    }

}
