//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * A loan servicing notification used to communicate changes in facility-level rates (e.g. penalty rate, default rate etc.).
 * 
 * <p>Java class for FacilityRateChangeNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacilityRateChangeNotification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}AbstractFacilityNotification"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.fpml.org/FpML-5/master}facilityRateChangeGroup" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}FacilityDetails.model"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}LoanContractDetails.model" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="party" type="{http://www.fpml.org/FpML-5/master}Party" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacilityRateChangeNotification", propOrder = {
    "facilityRateChangeGroup",
    "facilityIdentifier",
    "facilitySummary",
    "loanContractDetailsModel",
    "party"
})
public class FacilityRateChangeNotification
    extends AbstractFacilityNotification
{

    @XmlElementRef(name = "facilityRateChangeGroup", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends FacilityContractEvent> facilityRateChangeGroup;
    protected FacilityIdentifier facilityIdentifier;
    protected FacilitySummary facilitySummary;
    @XmlElements({
        @XmlElement(name = "contractIdentifier", type = FacilityContractIdentifier.class),
        @XmlElement(name = "contractSummary", type = LoanContractSummary.class),
        @XmlElement(name = "contract", type = LoanContract.class)
    })
    protected List<Object> loanContractDetailsModel;
    protected List<Party> party;

    /**
     * Gets the value of the facilityRateChangeGroup property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PenaltyRateExpiry }{@code >}
     *     {@link JAXBElement }{@code <}{@link DefaultRateExpiry }{@code >}
     *     {@link JAXBElement }{@code <}{@link PenaltyRateChange }{@code >}
     *     {@link JAXBElement }{@code <}{@link MandatoryCostRateExpiry }{@code >}
     *     {@link JAXBElement }{@code <}{@link MandatoryCostRateChange }{@code >}
     *     {@link JAXBElement }{@code <}{@link DefaultRateChange }{@code >}
     *     {@link JAXBElement }{@code <}{@link FacilityContractEvent }{@code >}
     *     
     */
    public JAXBElement<? extends FacilityContractEvent> getFacilityRateChangeGroup() {
        return facilityRateChangeGroup;
    }

    /**
     * Sets the value of the facilityRateChangeGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PenaltyRateExpiry }{@code >}
     *     {@link JAXBElement }{@code <}{@link DefaultRateExpiry }{@code >}
     *     {@link JAXBElement }{@code <}{@link PenaltyRateChange }{@code >}
     *     {@link JAXBElement }{@code <}{@link MandatoryCostRateExpiry }{@code >}
     *     {@link JAXBElement }{@code <}{@link MandatoryCostRateChange }{@code >}
     *     {@link JAXBElement }{@code <}{@link DefaultRateChange }{@code >}
     *     {@link JAXBElement }{@code <}{@link FacilityContractEvent }{@code >}
     *     
     */
    public void setFacilityRateChangeGroup(JAXBElement<? extends FacilityContractEvent> value) {
        this.facilityRateChangeGroup = value;
    }

    /**
     * Gets the value of the facilityIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityIdentifier }
     *     
     */
    public FacilityIdentifier getFacilityIdentifier() {
        return facilityIdentifier;
    }

    /**
     * Sets the value of the facilityIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityIdentifier }
     *     
     */
    public void setFacilityIdentifier(FacilityIdentifier value) {
        this.facilityIdentifier = value;
    }

    /**
     * Gets the value of the facilitySummary property.
     * 
     * @return
     *     possible object is
     *     {@link FacilitySummary }
     *     
     */
    public FacilitySummary getFacilitySummary() {
        return facilitySummary;
    }

    /**
     * Sets the value of the facilitySummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilitySummary }
     *     
     */
    public void setFacilitySummary(FacilitySummary value) {
        this.facilitySummary = value;
    }

    /**
     * Gets the value of the loanContractDetailsModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanContractDetailsModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanContractDetailsModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacilityContractIdentifier }
     * {@link LoanContractSummary }
     * {@link LoanContract }
     * 
     * 
     */
    public List<Object> getLoanContractDetailsModel() {
        if (loanContractDetailsModel == null) {
            loanContractDetailsModel = new ArrayList<Object>();
        }
        return this.loanContractDetailsModel;
    }

    /**
     * Gets the value of the party property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the party property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Party }
     * 
     * 
     */
    public List<Party> getParty() {
        if (party == null) {
            party = new ArrayList<Party>();
        }
        return this.party;
    }

}
