//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * A type defining the characteristics of the gas being traded in a physically settled gas transaction.
 * 
 * <p>Java class for GasProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GasProduct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.fpml.org/FpML-5/master}GasProductTypeEnum" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="calorificValue" type="{http://www.fpml.org/FpML-5/master}NonNegativeDecimal"/&gt;
 *           &lt;element name="quality" type="{http://www.fpml.org/FpML-5/master}GasQuality"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasProduct", propOrder = {
    "type",
    "calorificValue",
    "quality"
})
public class GasProduct {

    @XmlSchemaType(name = "token")
    protected GasProductTypeEnum type;
    protected BigDecimal calorificValue;
    protected GasQuality quality;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link GasProductTypeEnum }
     *     
     */
    public GasProductTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasProductTypeEnum }
     *     
     */
    public void setType(GasProductTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the calorificValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalorificValue() {
        return calorificValue;
    }

    /**
     * Sets the value of the calorificValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCalorificValue(BigDecimal value) {
        this.calorificValue = value;
    }

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link GasQuality }
     *     
     */
    public GasQuality getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasQuality }
     *     
     */
    public void setQuality(GasQuality value) {
        this.quality = value;
    }

}
