//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndependentAmountConventionEnum.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IndependentAmountConventionEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="NettedAfterThreshold"/&gt;
 *     &lt;enumeration value="NettedBeforeThreshold"/&gt;
 *     &lt;enumeration value="Segregated"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IndependentAmountConventionEnum")
@XmlEnum
public enum IndependentAmountConventionEnum {

    @XmlEnumValue("NettedAfterThreshold")
    NETTED_AFTER_THRESHOLD("NettedAfterThreshold"),
    @XmlEnumValue("NettedBeforeThreshold")
    NETTED_BEFORE_THRESHOLD("NettedBeforeThreshold"),
    @XmlEnumValue("Segregated")
    SEGREGATED("Segregated");
    private final String value;

    IndependentAmountConventionEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IndependentAmountConventionEnum fromValue(String v) {
        for (IndependentAmountConventionEnum c: IndependentAmountConventionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
