//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes an observation that caused a barrier knock out to trigger
 * 
 * <p>Java class for KnockOutRateObservation complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KnockOutRateObservation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}TriggerRateObservation"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rebatePayment" type="{http://www.fpml.org/FpML-5/master}NonNegativePayment" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KnockOutRateObservation", propOrder = {
    "rebatePayment"
})
public class KnockOutRateObservation
    extends TriggerRateObservation
{

    protected NonNegativePayment rebatePayment;

    /**
     * Gets the value of the rebatePayment property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativePayment }
     *     
     */
    public NonNegativePayment getRebatePayment() {
        return rebatePayment;
    }

    /**
     * Sets the value of the rebatePayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativePayment }
     *     
     */
    public void setRebatePayment(NonNegativePayment value) {
        this.rebatePayment = value;
    }

}
