//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * An abstract base type defining common features of a syndicated loan business event. Such events are originated by the borrower and are required to be communicated to the lender syndicate by agents.
 * 
 * <p>Java class for LoanEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanEvent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}AbstractEventRequireId"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="businessEventGroupId" type="{http://www.fpml.org/FpML-5/master}BusinessEventGroupIdentifier" minOccurs="0"/&gt;
 *         &lt;element name="previousInaccurateEventId" type="{http://www.fpml.org/FpML-5/master}BusinessEventIdentifier" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}BusinessEventParties.model"/&gt;
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/master}LenderAndCashDetails.model" minOccurs="0"/&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanEvent", propOrder = {
    "businessEventGroupId",
    "previousInaccurateEventId",
    "agentPartyReference",
    "borrowerPartyReference",
    "effectiveDate",
    "lenderPartyReference",
    "cashPayable",
    "comment"
})
@XmlSeeAlso({
    LoanContractEvent.class,
    LcEvent.class,
    FacilityContractEvent.class,
    FacilityEvent.class
})
public abstract class LoanEvent
    extends AbstractEventRequireId
{

    protected BusinessEventGroupIdentifier businessEventGroupId;
    protected BusinessEventIdentifier previousInaccurateEventId;
    protected PartyReference agentPartyReference;
    protected PartyReference borrowerPartyReference;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    protected PartyReference lenderPartyReference;
    protected CashPayable cashPayable;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String comment;

    /**
     * Gets the value of the businessEventGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessEventGroupIdentifier }
     *     
     */
    public BusinessEventGroupIdentifier getBusinessEventGroupId() {
        return businessEventGroupId;
    }

    /**
     * Sets the value of the businessEventGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessEventGroupIdentifier }
     *     
     */
    public void setBusinessEventGroupId(BusinessEventGroupIdentifier value) {
        this.businessEventGroupId = value;
    }

    /**
     * Gets the value of the previousInaccurateEventId property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessEventIdentifier }
     *     
     */
    public BusinessEventIdentifier getPreviousInaccurateEventId() {
        return previousInaccurateEventId;
    }

    /**
     * Sets the value of the previousInaccurateEventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessEventIdentifier }
     *     
     */
    public void setPreviousInaccurateEventId(BusinessEventIdentifier value) {
        this.previousInaccurateEventId = value;
    }

    /**
     * Gets the value of the agentPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getAgentPartyReference() {
        return agentPartyReference;
    }

    /**
     * Sets the value of the agentPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setAgentPartyReference(PartyReference value) {
        this.agentPartyReference = value;
    }

    /**
     * Gets the value of the borrowerPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getBorrowerPartyReference() {
        return borrowerPartyReference;
    }

    /**
     * Sets the value of the borrowerPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setBorrowerPartyReference(PartyReference value) {
        this.borrowerPartyReference = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the lenderPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getLenderPartyReference() {
        return lenderPartyReference;
    }

    /**
     * Sets the value of the lenderPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setLenderPartyReference(PartyReference value) {
        this.lenderPartyReference = value;
    }

    /**
     * Gets the value of the cashPayable property.
     * 
     * @return
     *     possible object is
     *     {@link CashPayable }
     *     
     */
    public CashPayable getCashPayable() {
        return cashPayable;
    }

    /**
     * Sets the value of the cashPayable property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashPayable }
     *     
     */
    public void setCashPayable(CashPayable value) {
        this.cashPayable = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
