//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * An entity for defining the master confirmation agreement executed between the parties.
 * 
 * <p>Java class for MasterConfirmation complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MasterConfirmation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="masterConfirmationType" type="{http://www.fpml.org/FpML-5/master}MasterConfirmationType" minOccurs="0"/&gt;
 *         &lt;element name="masterConfirmationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="masterConfirmationAnnexDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="masterConfirmationAnnexType" type="{http://www.fpml.org/FpML-5/master}MasterConfirmationAnnexType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MasterConfirmation", propOrder = {
    "masterConfirmationType",
    "masterConfirmationDate",
    "masterConfirmationAnnexDate",
    "masterConfirmationAnnexType"
})
public class MasterConfirmation {

    protected MasterConfirmationType masterConfirmationType;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar masterConfirmationDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar masterConfirmationAnnexDate;
    protected MasterConfirmationAnnexType masterConfirmationAnnexType;

    /**
     * Gets the value of the masterConfirmationType property.
     * 
     * @return
     *     possible object is
     *     {@link MasterConfirmationType }
     *     
     */
    public MasterConfirmationType getMasterConfirmationType() {
        return masterConfirmationType;
    }

    /**
     * Sets the value of the masterConfirmationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterConfirmationType }
     *     
     */
    public void setMasterConfirmationType(MasterConfirmationType value) {
        this.masterConfirmationType = value;
    }

    /**
     * Gets the value of the masterConfirmationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMasterConfirmationDate() {
        return masterConfirmationDate;
    }

    /**
     * Sets the value of the masterConfirmationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMasterConfirmationDate(XMLGregorianCalendar value) {
        this.masterConfirmationDate = value;
    }

    /**
     * Gets the value of the masterConfirmationAnnexDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMasterConfirmationAnnexDate() {
        return masterConfirmationAnnexDate;
    }

    /**
     * Sets the value of the masterConfirmationAnnexDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMasterConfirmationAnnexDate(XMLGregorianCalendar value) {
        this.masterConfirmationAnnexDate = value;
    }

    /**
     * Gets the value of the masterConfirmationAnnexType property.
     * 
     * @return
     *     possible object is
     *     {@link MasterConfirmationAnnexType }
     *     
     */
    public MasterConfirmationAnnexType getMasterConfirmationAnnexType() {
        return masterConfirmationAnnexType;
    }

    /**
     * Sets the value of the masterConfirmationAnnexType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterConfirmationAnnexType }
     *     
     */
    public void setMasterConfirmationAnnexType(MasterConfirmationAnnexType value) {
        this.masterConfirmationAnnexType = value;
    }

}
