//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * The physical delivery conditions for the transaction.
 * 
 * <p>Java class for MetalDelivery complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetalDelivery"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="deliveryLocation" type="{http://www.fpml.org/FpML-5/master}CommodityDeliveryPoint" minOccurs="0"/&gt;
 *         &lt;element name="risk" type="{http://www.fpml.org/FpML-5/master}CommodityDeliveryRisk" minOccurs="0"/&gt;
 *         &lt;element name="totalQuantityTolerance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="periodQuantityTolerance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="title" type="{http://www.fpml.org/FpML-5/master}MetalTitleEnum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetalDelivery", propOrder = {
    "deliveryLocation",
    "risk",
    "totalQuantityTolerance",
    "periodQuantityTolerance",
    "title"
})
public class MetalDelivery {

    protected CommodityDeliveryPoint deliveryLocation;
    protected CommodityDeliveryRisk risk;
    protected BigDecimal totalQuantityTolerance;
    protected BigDecimal periodQuantityTolerance;
    @XmlSchemaType(name = "token")
    protected MetalTitleEnum title;

    /**
     * Gets the value of the deliveryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityDeliveryPoint }
     *     
     */
    public CommodityDeliveryPoint getDeliveryLocation() {
        return deliveryLocation;
    }

    /**
     * Sets the value of the deliveryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityDeliveryPoint }
     *     
     */
    public void setDeliveryLocation(CommodityDeliveryPoint value) {
        this.deliveryLocation = value;
    }

    /**
     * Gets the value of the risk property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityDeliveryRisk }
     *     
     */
    public CommodityDeliveryRisk getRisk() {
        return risk;
    }

    /**
     * Sets the value of the risk property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityDeliveryRisk }
     *     
     */
    public void setRisk(CommodityDeliveryRisk value) {
        this.risk = value;
    }

    /**
     * Gets the value of the totalQuantityTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalQuantityTolerance() {
        return totalQuantityTolerance;
    }

    /**
     * Sets the value of the totalQuantityTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalQuantityTolerance(BigDecimal value) {
        this.totalQuantityTolerance = value;
    }

    /**
     * Gets the value of the periodQuantityTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPeriodQuantityTolerance() {
        return periodQuantityTolerance;
    }

    /**
     * Sets the value of the periodQuantityTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPeriodQuantityTolerance(BigDecimal value) {
        this.periodQuantityTolerance = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link MetalTitleEnum }
     *     
     */
    public MetalTitleEnum getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetalTitleEnum }
     *     
     */
    public void setTitle(MetalTitleEnum value) {
        this.title = value;
    }

}
