//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A type to hold the other provisions schemes.
 * 
 * <p>Java class for OtherProvisions complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherProvisions"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.fpml.org/FpML-5/master&gt;Scheme"&gt;
 *       &lt;attribute name="otherProvisionsEnglishLawScheme" type="{http://www.fpml.org/FpML-5/master}NonEmptyURI" default="http://www.fpml.org/coding-scheme/other-provisions-english-law" /&gt;
 *       &lt;attribute name="otherProvisionsNewYorkLawScheme" type="{http://www.fpml.org/FpML-5/master}NonEmptyURI" default="http://www.fpml.org/coding-scheme/other-provisions-new-york-law" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherProvisions", propOrder = {
    "value"
})
public class OtherProvisions {

    @XmlValue
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String value;
    @XmlAttribute(name = "otherProvisionsEnglishLawScheme")
    protected String otherProvisionsEnglishLawScheme;
    @XmlAttribute(name = "otherProvisionsNewYorkLawScheme")
    protected String otherProvisionsNewYorkLawScheme;

    /**
     * The base class for all types which define coding schemes that are allowed to be empty.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the otherProvisionsEnglishLawScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherProvisionsEnglishLawScheme() {
        if (otherProvisionsEnglishLawScheme == null) {
            return "http://www.fpml.org/coding-scheme/other-provisions-english-law";
        } else {
            return otherProvisionsEnglishLawScheme;
        }
    }

    /**
     * Sets the value of the otherProvisionsEnglishLawScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherProvisionsEnglishLawScheme(String value) {
        this.otherProvisionsEnglishLawScheme = value;
    }

    /**
     * Gets the value of the otherProvisionsNewYorkLawScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherProvisionsNewYorkLawScheme() {
        if (otherProvisionsNewYorkLawScheme == null) {
            return "http://www.fpml.org/coding-scheme/other-provisions-new-york-law";
        } else {
            return otherProvisionsNewYorkLawScheme;
        }
    }

    /**
     * Sets the value of the otherProvisionsNewYorkLawScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherProvisionsNewYorkLawScheme(String value) {
        this.otherProvisionsNewYorkLawScheme = value;
    }

}
