//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeriodEnum.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PeriodEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="W"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="Y"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PeriodEnum")
@XmlEnum
public enum PeriodEnum {


    /**
     * Day.
     * 
     */
    D,

    /**
     * Week.
     * 
     */
    W,

    /**
     * Month.
     * 
     */
    M,

    /**
     * Year.
     * 
     */
    Y;

    public String value() {
        return name();
    }

    public static PeriodEnum fromValue(String v) {
        return valueOf(v);
    }

}
