//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The limits associated with rates that can be applied to a loan instrument.
 * 
 * <p>Java class for RateLimits complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateLimits"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="floorRate" type="{http://www.fpml.org/FpML-5/master}PeriodRate" minOccurs="0"/&gt;
 *         &lt;element name="capRate" type="{http://www.fpml.org/FpML-5/master}PeriodRate" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateLimits", propOrder = {
    "floorRate",
    "capRate"
})
public class RateLimits {

    protected PeriodRate floorRate;
    protected PeriodRate capRate;

    /**
     * Gets the value of the floorRate property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodRate }
     *     
     */
    public PeriodRate getFloorRate() {
        return floorRate;
    }

    /**
     * Sets the value of the floorRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodRate }
     *     
     */
    public void setFloorRate(PeriodRate value) {
        this.floorRate = value;
    }

    /**
     * Gets the value of the capRate property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodRate }
     *     
     */
    public PeriodRate getCapRate() {
        return capRate;
    }

    /**
     * Sets the value of the capRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodRate }
     *     
     */
    public void setCapRate(PeriodRate value) {
        this.capRate = value;
    }

}
