//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * A loan servicing retraction designed to cancel a previous rollover transaction.
 * 
 * <p>Java class for RolloverNotificationRetracted complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RolloverNotificationRetracted"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}NonCorrectableRequestMessage"&gt;
 *       &lt;sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="businessEventGroupId" type="{http://www.fpml.org/FpML-5/master}BusinessEventGroupIdentifier" minOccurs="0"/&gt;
 *           &lt;element name="party" type="{http://www.fpml.org/FpML-5/master}Party" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="maturingContracts"&gt;
 *               &lt;complexType&gt;
 *                 &lt;complexContent&gt;
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                     &lt;group ref="{http://www.fpml.org/FpML-5/master}LoanContractDetails.model" maxOccurs="unbounded"/&gt;
 *                   &lt;/restriction&gt;
 *                 &lt;/complexContent&gt;
 *               &lt;/complexType&gt;
 *             &lt;/element&gt;
 *             &lt;element name="currentContracts"&gt;
 *               &lt;complexType&gt;
 *                 &lt;complexContent&gt;
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element name="contract" type="{http://www.fpml.org/FpML-5/master}LoanContract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                     &lt;/sequence&gt;
 *                   &lt;/restriction&gt;
 *                 &lt;/complexContent&gt;
 *               &lt;/complexType&gt;
 *             &lt;/element&gt;
 *           &lt;/sequence&gt;
 *           &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *             &lt;element name="baseRateSet" type="{http://www.fpml.org/FpML-5/master}LoanContractBaseRateSet"/&gt;
 *             &lt;element name="borrowing" type="{http://www.fpml.org/FpML-5/master}Borrowing"/&gt;
 *             &lt;element name="commitmentAdjustment" type="{http://www.fpml.org/FpML-5/master}CommitmentAdjustment"/&gt;
 *             &lt;element name="interestCapitalization" type="{http://www.fpml.org/FpML-5/master}InterestCapitalization"/&gt;
 *             &lt;element name="interestPayment" type="{http://www.fpml.org/FpML-5/master}InterestPayment"/&gt;
 *             &lt;element name="repayment" type="{http://www.fpml.org/FpML-5/master}Repayment"/&gt;
 *           &lt;/choice&gt;
 *           &lt;group ref="{http://www.fpml.org/FpML-5/master}FacilityDetails.model"/&gt;
 *           &lt;element name="party" type="{http://www.fpml.org/FpML-5/master}Party" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RolloverNotificationRetracted", propOrder = {
    "rest"
})
public class RolloverNotificationRetracted
    extends NonCorrectableRequestMessage
{

    @XmlElementRefs({
        @XmlElementRef(name = "businessEventGroupId", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "party", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "maturingContracts", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "currentContracts", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "baseRateSet", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "borrowing", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "commitmentAdjustment", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interestCapitalization", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interestPayment", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "repayment", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "facilityIdentifier", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "facilitySummary", namespace = "http://www.fpml.org/FpML-5/master", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> rest;

    /**
     * Gets the rest of the content model. 
     *         
     *         <p>
     *         You are getting this "catch-all" property because of the following reason: 
     *         The field name "Party" is used by two different parts of a schema. See: 
     *         line 3663 of file:/Users/silvionetto/IdeaProjects/gapp/src/main/resources/schema/fpml-loan.xsd
     *         line 3603 of file:/Users/silvionetto/IdeaProjects/gapp/src/main/resources/schema/fpml-loan.xsd
     *         <p>
     *         To get rid of this property, apply a property customization to one 
     *         of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BusinessEventGroupIdentifier }{@code >}
     * {@link JAXBElement }{@code <}{@link Party }{@code >}
     * {@link JAXBElement }{@code <}{@link MaturingContracts }{@code >}
     * {@link JAXBElement }{@code <}{@link CurrentContracts }{@code >}
     * {@link JAXBElement }{@code <}{@link LoanContractBaseRateSet }{@code >}
     * {@link JAXBElement }{@code <}{@link Borrowing }{@code >}
     * {@link JAXBElement }{@code <}{@link CommitmentAdjustment }{@code >}
     * {@link JAXBElement }{@code <}{@link InterestCapitalization }{@code >}
     * {@link JAXBElement }{@code <}{@link InterestPayment }{@code >}
     * {@link JAXBElement }{@code <}{@link Repayment }{@code >}
     * {@link JAXBElement }{@code <}{@link FacilityIdentifier }{@code >}
     * {@link JAXBElement }{@code <}{@link FacilitySummary }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="contract" type="{http://www.fpml.org/FpML-5/master}LoanContract" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contract"
    })
    public static class CurrentContracts {

        protected List<LoanContract> contract;

        /**
         * Gets the value of the contract property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contract property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContract().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LoanContract }
         * 
         * 
         */
        public List<LoanContract> getContract() {
            if (contract == null) {
                contract = new ArrayList<LoanContract>();
            }
            return this.contract;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;group ref="{http://www.fpml.org/FpML-5/master}LoanContractDetails.model" maxOccurs="unbounded"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "loanContractDetailsModel"
    })
    public static class MaturingContracts {

        @XmlElements({
            @XmlElement(name = "contractIdentifier", type = FacilityContractIdentifier.class),
            @XmlElement(name = "contractSummary", type = LoanContractSummary.class),
            @XmlElement(name = "contract", type = LoanContract.class)
        })
        protected List<Object> loanContractDetailsModel;

        /**
         * Gets the value of the loanContractDetailsModel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the loanContractDetailsModel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLoanContractDetailsModel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FacilityContractIdentifier }
         * {@link LoanContractSummary }
         * {@link LoanContract }
         * 
         * 
         */
        public List<Object> getLoanContractDetailsModel() {
            if (loanContractDetailsModel == null) {
                loanContractDetailsModel = new ArrayList<Object>();
            }
            return this.loanContractDetailsModel;
        }

    }

}
