//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The New York Law 2013 SCSA implementation, which extends StandardCreditSupportAnnexBase.
 * 
 * <p>Java class for StandardCreditSupportAnnex2013NewYorkLaw complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StandardCreditSupportAnnex2013NewYorkLaw"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/master}StandardCreditSupportAnnexBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="disputeResolution" type="{http://www.fpml.org/FpML-5/master}DisputeResolution" minOccurs="0"/&gt;
 *         &lt;element name="demandsAndNotices" type="{http://www.fpml.org/FpML-5/master}PartyContactInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="otherProvisions" type="{http://www.fpml.org/FpML-5/master}OtherProvisions" minOccurs="0"/&gt;
 *         &lt;element name="transportCurrency" type="{http://www.fpml.org/FpML-5/master}TransportCurrency" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="dayCount" type="{http://www.fpml.org/FpML-5/master}DayCount" minOccurs="0"/&gt;
 *         &lt;element name="independentAmountInterestRate" type="{http://www.fpml.org/FpML-5/master}IndependentAmountInterestRate" minOccurs="0"/&gt;
 *         &lt;element name="independentAmountEligibleCollateral" type="{http://www.fpml.org/FpML-5/master}IndependentAmountEligibleCollateral" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="holdingAndUsingPostedCollateral" type="{http://www.fpml.org/FpML-5/master}HoldingAndUsingPostedCollateral" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardCreditSupportAnnex2013NewYorkLaw", propOrder = {
    "disputeResolution",
    "demandsAndNotices",
    "otherProvisions",
    "transportCurrency",
    "dayCount",
    "independentAmountInterestRate",
    "independentAmountEligibleCollateral",
    "holdingAndUsingPostedCollateral"
})
public class StandardCreditSupportAnnex2013NewYorkLaw
    extends StandardCreditSupportAnnexBase
{

    protected DisputeResolution disputeResolution;
    protected List<PartyContactInformation> demandsAndNotices;
    protected OtherProvisions otherProvisions;
    protected List<TransportCurrency> transportCurrency;
    protected DayCount dayCount;
    protected IndependentAmountInterestRate independentAmountInterestRate;
    protected List<IndependentAmountEligibleCollateral> independentAmountEligibleCollateral;
    protected List<HoldingAndUsingPostedCollateral> holdingAndUsingPostedCollateral;

    /**
     * Gets the value of the disputeResolution property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeResolution }
     *     
     */
    public DisputeResolution getDisputeResolution() {
        return disputeResolution;
    }

    /**
     * Sets the value of the disputeResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeResolution }
     *     
     */
    public void setDisputeResolution(DisputeResolution value) {
        this.disputeResolution = value;
    }

    /**
     * Gets the value of the demandsAndNotices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the demandsAndNotices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDemandsAndNotices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyContactInformation }
     * 
     * 
     */
    public List<PartyContactInformation> getDemandsAndNotices() {
        if (demandsAndNotices == null) {
            demandsAndNotices = new ArrayList<PartyContactInformation>();
        }
        return this.demandsAndNotices;
    }

    /**
     * Gets the value of the otherProvisions property.
     * 
     * @return
     *     possible object is
     *     {@link OtherProvisions }
     *     
     */
    public OtherProvisions getOtherProvisions() {
        return otherProvisions;
    }

    /**
     * Sets the value of the otherProvisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherProvisions }
     *     
     */
    public void setOtherProvisions(OtherProvisions value) {
        this.otherProvisions = value;
    }

    /**
     * Gets the value of the transportCurrency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportCurrency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportCurrency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportCurrency }
     * 
     * 
     */
    public List<TransportCurrency> getTransportCurrency() {
        if (transportCurrency == null) {
            transportCurrency = new ArrayList<TransportCurrency>();
        }
        return this.transportCurrency;
    }

    /**
     * Gets the value of the dayCount property.
     * 
     * @return
     *     possible object is
     *     {@link DayCount }
     *     
     */
    public DayCount getDayCount() {
        return dayCount;
    }

    /**
     * Sets the value of the dayCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayCount }
     *     
     */
    public void setDayCount(DayCount value) {
        this.dayCount = value;
    }

    /**
     * Gets the value of the independentAmountInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link IndependentAmountInterestRate }
     *     
     */
    public IndependentAmountInterestRate getIndependentAmountInterestRate() {
        return independentAmountInterestRate;
    }

    /**
     * Sets the value of the independentAmountInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndependentAmountInterestRate }
     *     
     */
    public void setIndependentAmountInterestRate(IndependentAmountInterestRate value) {
        this.independentAmountInterestRate = value;
    }

    /**
     * Gets the value of the independentAmountEligibleCollateral property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the independentAmountEligibleCollateral property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndependentAmountEligibleCollateral().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndependentAmountEligibleCollateral }
     * 
     * 
     */
    public List<IndependentAmountEligibleCollateral> getIndependentAmountEligibleCollateral() {
        if (independentAmountEligibleCollateral == null) {
            independentAmountEligibleCollateral = new ArrayList<IndependentAmountEligibleCollateral>();
        }
        return this.independentAmountEligibleCollateral;
    }

    /**
     * Gets the value of the holdingAndUsingPostedCollateral property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the holdingAndUsingPostedCollateral property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHoldingAndUsingPostedCollateral().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HoldingAndUsingPostedCollateral }
     * 
     * 
     */
    public List<HoldingAndUsingPostedCollateral> getHoldingAndUsingPostedCollateral() {
        if (holdingAndUsingPostedCollateral == null) {
            holdingAndUsingPostedCollateral = new ArrayList<HoldingAndUsingPostedCollateral>();
        }
        return this.holdingAndUsingPostedCollateral;
    }

}
