//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.10 at 05:14:53 PM CET 
//


package org.fpml.fpml_5.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * A type defining trade related information which is not product specific.
 * 
 * <p>Java class for TradeHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeHeader"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="partyTradeIdentifier" type="{http://www.fpml.org/FpML-5/master}PartyTradeIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tradeInformation" type="{http://www.fpml.org/FpML-5/master}TradeInformation" minOccurs="0"/&gt;
 *         &lt;element name="partyTradeInformation" type="{http://www.fpml.org/FpML-5/master}PartyTradeInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tradeSummary" type="{http://www.fpml.org/FpML-5/master}TradeSummary" minOccurs="0"/&gt;
 *         &lt;element name="productSummary" type="{http://www.fpml.org/FpML-5/master}ProductSummary" minOccurs="0"/&gt;
 *         &lt;element name="originatingPackage" type="{http://www.fpml.org/FpML-5/master}PackageSummary" minOccurs="0"/&gt;
 *         &lt;element name="tradeDate" type="{http://www.fpml.org/FpML-5/master}IdentifiedDate" minOccurs="0"/&gt;
 *         &lt;element name="clearedDate" type="{http://www.fpml.org/FpML-5/master}IdentifiedDate" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeHeader", propOrder = {
    "partyTradeIdentifier",
    "tradeInformation",
    "partyTradeInformation",
    "tradeSummary",
    "productSummary",
    "originatingPackage",
    "tradeDate",
    "clearedDate"
})
public class TradeHeader {

    protected List<PartyTradeIdentifier> partyTradeIdentifier;
    protected TradeInformation tradeInformation;
    protected List<PartyTradeInformation> partyTradeInformation;
    protected TradeSummary tradeSummary;
    protected ProductSummary productSummary;
    protected PackageSummary originatingPackage;
    protected IdentifiedDate tradeDate;
    protected IdentifiedDate clearedDate;

    /**
     * Gets the value of the partyTradeIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyTradeIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyTradeIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyTradeIdentifier }
     * 
     * 
     */
    public List<PartyTradeIdentifier> getPartyTradeIdentifier() {
        if (partyTradeIdentifier == null) {
            partyTradeIdentifier = new ArrayList<PartyTradeIdentifier>();
        }
        return this.partyTradeIdentifier;
    }

    /**
     * Gets the value of the tradeInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TradeInformation }
     *     
     */
    public TradeInformation getTradeInformation() {
        return tradeInformation;
    }

    /**
     * Sets the value of the tradeInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeInformation }
     *     
     */
    public void setTradeInformation(TradeInformation value) {
        this.tradeInformation = value;
    }

    /**
     * Gets the value of the partyTradeInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyTradeInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyTradeInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyTradeInformation }
     * 
     * 
     */
    public List<PartyTradeInformation> getPartyTradeInformation() {
        if (partyTradeInformation == null) {
            partyTradeInformation = new ArrayList<PartyTradeInformation>();
        }
        return this.partyTradeInformation;
    }

    /**
     * Gets the value of the tradeSummary property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSummary }
     *     
     */
    public TradeSummary getTradeSummary() {
        return tradeSummary;
    }

    /**
     * Sets the value of the tradeSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSummary }
     *     
     */
    public void setTradeSummary(TradeSummary value) {
        this.tradeSummary = value;
    }

    /**
     * Gets the value of the productSummary property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSummary }
     *     
     */
    public ProductSummary getProductSummary() {
        return productSummary;
    }

    /**
     * Sets the value of the productSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSummary }
     *     
     */
    public void setProductSummary(ProductSummary value) {
        this.productSummary = value;
    }

    /**
     * Gets the value of the originatingPackage property.
     * 
     * @return
     *     possible object is
     *     {@link PackageSummary }
     *     
     */
    public PackageSummary getOriginatingPackage() {
        return originatingPackage;
    }

    /**
     * Sets the value of the originatingPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageSummary }
     *     
     */
    public void setOriginatingPackage(PackageSummary value) {
        this.originatingPackage = value;
    }

    /**
     * Gets the value of the tradeDate property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiedDate }
     *     
     */
    public IdentifiedDate getTradeDate() {
        return tradeDate;
    }

    /**
     * Sets the value of the tradeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiedDate }
     *     
     */
    public void setTradeDate(IdentifiedDate value) {
        this.tradeDate = value;
    }

    /**
     * Gets the value of the clearedDate property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiedDate }
     *     
     */
    public IdentifiedDate getClearedDate() {
        return clearedDate;
    }

    /**
     * Sets the value of the clearedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiedDate }
     *     
     */
    public void setClearedDate(IdentifiedDate value) {
        this.clearedDate = value;
    }

}
