import groovy.sql.Sql

def url = 'jdbc:hsqldb:gappDB'
def user = 'sa'
def password = ''
def driver = 'org.hsqldb.jdbcDriver'
def sql = Sql.newInstance(url, user, password, driver)

// ... create 'sql' instance
sql.execute '''
  CREATE TABLE TB_Users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_name   VARCHAR(64),
    user_password    VARCHAR(64),
    version     INTEGER
  );
  CREATE TABLE TB_Roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_user     INTEGER,
    name    VARCHAR(64),
    version     INTEGER
  );
'''
// close 'sql' instance ...

sql.close()