package com.ing.scripts

import groovy.sql.Sql

def url = 'jdbc:hsqldb:gappDB'
def user = 'sa'
def password = ''
def driver = 'org.hsqldb.jdbcDriver'
def sql = Sql.newInstance(url, user, password, driver)

// ... create 'sql' instance
sql.execute '''
  CREATE TABLE TB_Overnight (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    overnightDate DATE DEFAULT CURRENT_DATE,
    bank        INTEGER,
    amount      DECIMAL(10,2),
    rate        FLOAT,
    version     INTEGER
  );
'''

sql.execute "INSERT INTO TB_Overnight(bank, amount, rate, version) VALUES (0, 100000, 1.5, 0)"
sql.execute "INSERT INTO TB_Overnight(bank, amount, rate, version) VALUES (1, 20000, 1.1, 0)"
sql.execute "INSERT INTO TB_Overnight(bank, amount, rate, version) VALUES (2, 30000, 1.2, 0)"

sql.query('SELECT bank, amount, rate, version FROM TB_Overnight') { resultSet ->
    while (resultSet.next()) {
        def bank  = resultSet.getInt('bank')
        def amount = resultSet.getBigDecimal('amount')
        def rate = resultSet.getFloat('rate')
        def version = resultSet.getInt('version')
        println "${bank}:${amount}:${rate}:${version}"
    }
}

sql.close()