import groovy.sql.Sql

def url = 'jdbc:mysql://devdb.cc72u2l6fl7d.us-east-1.rds.amazonaws.com:3306/gappDB'
def user = 'gapp'
def password = 'gapp'
def driver = 'com.mysql.jdbc.Driver'
def sql = Sql.newInstance(url, user, password, driver)

// ... create 'sql' instance
sql.execute '''
  CREATE TABLE TB_Users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_name   VARCHAR(64),
    user_password    VARCHAR(64),
    version     INTEGER
  );
  CREATE TABLE TB_Roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_user     INTEGER,
    name        VARCHAR(64),
    version     INTEGER
  );
  CREATE TABLE TB_Currency (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(64),
    code        VARCHAR(3),
    version     INTEGER
  );
  CREATE TABLE TB_Bank (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(64),
    version     INTEGER
  );
  CREATE TABLE TB_Trade (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    type        VARCHAR(10),
    currency    VARCHAR(3),
    amount      DECIMAL(10,2),
    rateType    VARCHAR(5),
    version     INTEGER
  );
  CREATE TABLE TB_Overnight (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    overnightDate DATE DEFAULT CURRENT_DATE,
    bank        INTEGER,
    amount      DECIMAL(10,2),
    rate        FLOAT,
    version     INTEGER
  );
'''
// close 'sql' instance ...

sql.close()